name: ClusterFuzzLite batch fuzzing
on:
  schedule:
    - cron: '0 0/6 * * *' # Every 6th hour. Change this to whatever is suitable.
  workflow_dispatch:
permissions: read-all
jobs:
  BatchFuzzing:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        sanitizer:
          - address
          - undefined
          - memory
    steps:
      - name: Build Fuzzers (${{ matrix.sanitizer }})
        id: build
        uses: google/clusterfuzzlite/actions/build_fuzzers@v1
        with:
          language: c++
          sanitizer: ${{ matrix.sanitizer }}
          storage-repo: https://github.com/MTRNord/spank_olm_fuzz_storage.git
      - name: Run Fuzzers (${{ matrix.sanitizer }})
        id: run
        uses: google/clusterfuzzlite/actions/run_fuzzers@v1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          fuzz-seconds: 3600
          mode: 'batch'
          sanitizer: ${{ matrix.sanitizer }}
          output-sarif: true
          storage-repo: https://github.com/MTRNord/spank_olm_fuzz_storage.git