name: CI

on: [ push, pull_request, workflow_dispatch ]

permissions: { }

jobs:
  CI:
    name: ${{ matrix.name }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - name: "Linux x64 (Ubuntu Latest) - GCC 14"
            os: ubuntu-latest
            build: { cc: gcc-14, cxx: g++-14, linker: ld }

          - name: "macOS arm64 (latest) - Xcode"
            os: macos-latest
            build: { cc: clang, cxx: clang++, linker: ld.lld }

    env:
      CC: ${{ matrix.build.cc }}
      CXX: ${{ matrix.build.cxx }}
      LD: ${{ matrix.build.linker }}
      CPPFLAGS: -Wall -Werror

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Ubuntu dependencies
        if: runner.os == 'Linux'
        run: |
          sudo apt-get update
          sudo apt-get install \
            meson pkg-config

      - name: Install macOS dependencies
        if: runner.os == 'macOS'
        run: |
          pip3 install meson --break-system-packages
          brew install \
            ninja pkg-config


      - name: Prepare macOS environment
        if: runner.os == 'macOS'
        run: |
          echo "PKG_CONFIG_PATH=$(brew --prefix botan)/lib/pkgconfig:$PKG_CONFIG_PATH" >> $GITHUB_ENV

      - name: Build and install Botan
        run: |
          git clone --depth 1 https://github.com/randombit/botan.git
          pushd botan
          ./configure.py --prefix="${{ github.workspace }}/botan-install"
          make -j$(nproc)
          make install
          popd
          echo "PKG_CONFIG_PATH=${{ github.workspace }}/botan-install/lib/pkgconfig:$PKG_CONFIG_PATH" >> $GITHUB_ENV
          echo "CPPFLAGS=-I${{ github.workspace }}/botan-install/include $CPPFLAGS" >> $GITHUB_ENV
          echo "LDFLAGS=-L${{ github.workspace }}/botan-install/lib $LDFLAGS" >> $GITHUB_ENV

      - name: Configure spank-olm
        run: |
          meson setup build \
            -Ddebug=true \
          || (cat build/meson-logs/meson-log.txt && exit 1)

      - name: Build spank-olm
        run: meson compile -C build

      - name: Check spank-olm
        run: |
          meson test -C build \
          || (cat build/meson-logs/testlog.txt && exit 1)

      - name: Install spank-olm
        run: sudo meson install -C build

      - name: Rebuild the shared library cache
        if: runner.os == 'Linux'
        run: sudo ldconfig